const list = [
    {
      id: 1,
      title: "BagsInBundles",
      Manufacturer:"by Wonder House Co. | 25 April 2018",
      price: 30000,
      img: "./Images/Img.jpeg",
      amount: 1,
    },
    {
      id: 2,
      title: "Nike shoes",
      Manufacturer: "by Nike | 1 September 2020",
      price: 40000,
      img: "./Images/img12.jpeg",
      amount: 1,
    },
    {
      id: 3,
      title: "WH(T-Shirt)",
      Manufacturer: "by Wonder House Co. | 25 November 2018",
      price: 10500,
      img: "./Images/img1.jpeg",
      amount: 1,
    },
    {
      id: 4,
      title: "WH-Bbag",
      Manufacturer: "by Wonder House Store | 25 April 2018",
      price: 20300,
      img: "./Images/img14.jpeg",
      amount: 1,
    },
    {
      id: 5,
      title: "WH-SmallBag",
      Manufacturer: "by Wonder House Co.  | 1 January 2018",
      price: 12000,
      img: "./Images/img13.jpeg",
      amount: 1,
    },
    {
      id: 6,
      title: "WH-Tshirt",
      Manufacturer: "by Wonder House Co | 30 September 2020",
      price: 14000,
      img: "./Images/img4.avif",
      amount: 1,
    },
    {
      id: 7,
      title: "WH-SleevelessDress ",
      Manufacturer: "by Wonder House Co.  | 1 January 2021",
      price: 35000,
      img: "./Images/img5.jpeg",
      amount: 1,
    },
    {
      id: 8,
      title: "WH-BaggyDress",
      Manufacturer: "by Wonder House Co. | 6 December 2020",
      price: 28900,
      img: "./Images/img6.jpeg",
      amount: 1,
    },
    {
      id: 9,
      title: "Wh-HikingShoes",
      Manufacturer: "by Wonder House Co.",
      price: 32000,
      img: "./Images/img11.jpeg",
      amount: 1,
    },
    {
      id: 10,
      title: "WH-HighAllStars",
      Manufacturer: "by Wonder House Co. | 1 September 2021",
      price: 11000,
      img: "./Images/img8.jpeg",
      amount: 1,
    },
    {
      id: 11,
      title: "Designer Shoes",
      Manufacturer: "by Designer Co  | 14 December 2021",
      price: 34000,
      img: "./Images/img9.jpeg",
      amount: 1,
    },
    {
      id: 12,
      title: "WH-Shoes",
      Manufacturer: "by Wonder House Co. | 1 January 2015",
      price: 15700,
      img: "./Images/img10.jpeg",
      amount: 1,
    },
];

export default list;